apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: dev-test-cluster
  namespace: dev-test

spec:
  settings:
    storage:
      defaultClass: k8s-storage-policy
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: k8s-storage-policy
      tkr:
        reference:
          name: v1.30.1---vmware.1-fips-tkg.5
    nodePools:
      - name: worker-pool
        replicas: 2
        vmClass: best-effort-medium
        storageClass: k8s-storage-policy
        tkr:
          reference:
            name: v1.30.1---vmware.1-fips-tkg.5
