apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: prod-zeon-cluster
  namespace: prod-zeon
spec:
  topology:
    controlPlane:
      # Рекомендация: для прод-окружения 3 CP-нод, для dev – достаточно 1
      replicas: 1
      vmClass: best-effort-small
      storageClass: k8s-storage-policy
      tkr:
        reference:
          name: v1.30.1---vmware.1-fips-tkg.5
    nodePools:
      - name: worker-pool
        # Рекомендация: для HA ≥3 воркеров, для теста – 1–2
        replicas: 2
        vmClass: best-effort-medium
        storageClass: k8s-storage-policy
        tkr:
          reference:
            name: v1.30.1---vmware.1-fips-tkg.5
