apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-setter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sysctl-setter
  template:
    metadata:
      labels:
        app: sysctl-setter
    spec:
      serviceAccountName: default
      hostPID: true
      containers:
      - name: sysctl
        image: busybox:1.34
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - sysctl -w vm.max_map_count=262144 && sleep infinity
        volumeMounts:
        - mountPath: /sys
          name: sys
      volumes:
      - name: sys
        hostPath:
          path: /sys
