apiVersion: v1
kind: Service
metadata:
  name: opensearch-lb
  namespace: opensearch-logger
spec:
  type: LoadBalancer
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
