apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: opensearch-logger
spec:
  clusterIP: None
  selector:
    app: opensearch
  ports:
    - name: transport
      port: 9300
    - name: http
      port: 9200
