apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: dev-test-cluster
  namespace: dev-test               # ваш vSphere Namespace
spec:
  topology:
    controlPlane:
      replicas: 1                   # dev-кластер, одной CP-ноды достаточно
      vmClass: best-effort-small
      storageClass: k8s-storage-policy
      tkr:
        reference:
          name: v1.30.1---vmware.1-fips-tkg.5
    nodePools:
      - name: worker-pool
        replicas: 2
        vmClass: best-effort-medium
        storageClass: k8s-storage-policy
        tkr:
          reference:
            name: v1.30.1---vmware.1-fips-tkg.5
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["100.96.0.0/11"]      # новый PodCIDR
      services:
        cidrBlocks: ["10.96.0.0/12"]       # дефолтный ServiceCIDR
