apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: zeon-prod-cluster
  namespace: zeon-prod

spec:
  topology:
    controlPlane:
      replicas: 3
      vmClass: best-effort-medium
      storageClass: k8s-sha-zeon-storage-policy
      tkr:
        reference:
          name: v1.30.1---vmware.1-fips-tkg.5
    nodePools:
      - name: worker-pool
        replicas: 0
        vmClass: best-effort-medium
        storageClass: k8s-sha-zeon-storage-policy
      - name: worker-large
        replicas: 5
        vmClass: best-effort-large
        storageClass: k8s-sha-zeon-storage-policy
        tkr:
          reference:
            name: v1.30.1---vmware.1-fips-tkg.5
  settings:
    storage:
      defaultClass: k8s-sha-zeon-storage-policy
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["100.97.0.0/11"]      # новый PodCIDR
      services:
        cidrBlocks: ["10.97.0.0/12"]       # дефолтный ServiceCIDR
