apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: tcp-postgres
      port: 5432        # внешний порт LB-VIP
      targetPort: 5432  # порт в контейнере
