apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: velero-minio
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
  selector:
    app: minio
